# GoReleaser-based release workflow
name: Release

on:
  push:
    # Trigger on semantic version tags like v1.2.3
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Run GoReleaser
        run: |
          go install github.com/goreleaser/goreleaser@latest
          goreleaser release --clean --config dist/config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}